image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Postinstall .NET 6.0 and dev certificates
    init: |
      mkdir -p /tmp/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir /tmp/dotnet
      dotnet tool install --global dotnet-ef
      export PATH="$PATH:/home/gitpod/.dotnet/tools" 
      dotnet dev-certs https 
      dotnet restore
  # - name: Postinstall of flutter and android SDK 
  #   command: |
  #     mkdir -p /home/gitpod/.android
  #     touch /home/gitpod/.android/repositories.cfg
  #     export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_SDK/cmdline-tools/bin:$ANDROID_PATH:$PATH
  #     /home/gitpod/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3" --sdk_root=$ANDROID_SDK
  #     flutter config --android-sdk $ANDROID_SDK
  #     flutter config --android-studio-dir $ANDROID_STUDIO

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - muhammad-sammy.csharp
    # - Dart-Code.flutter